#!/bin/bash
# A script to convert pictures to Spotify cover standards
# dependencies:
# sudo apt-get install imagemagick
# macOS: brew update && brew install imagemagick

echo 'Converting' $1 'to a Spotify cover'

convert -resize 300x300^ -extent 300x300 $1 $1_cover.jpg
