#!/bin/bash
# A script to get weather for a given city

echo -e "What city do you want the weather for?"
read city

echo "Weather for ${city}" 
curl -s "https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=00bbba62aab5f8af6e031f59ed80c87e" | tr ',' '\n' | grep -e description -e temp | sed -e 's/[\"{}:]/ /g' -e 's/description/ /g' -e 's/main//g'
